Dependency Injection WITH Spring - Spring Profiles   ---------------
  Allow you to control your Spring application in different runtime environments.
  You can for example on local dev environment use H2 in-memory database and on production use MySQL and the Spring profile will govern which beans are used.

  	@SpringBootApplication
  	public class SfgDiApplication {

  		public static void main(String[] args) {
  			ApplicationContext ctx = SpringApplication.run(SfgDiApplication.class, args);

  			I18nController i18nController = (I18nController) ctx.getBean("i18nController");
  			System.out.println(i18nController.sayHello());

  			...
  		}

  	}

  	@Controller
  	public class I18nController {

  		private final GreetingService greetingService;

  		@Autowired
  		public I18nController(@Qualifier("i18nService") GreetingService greetingService) {
  			this.greetingService = greetingService;
  		}

  		public String sayHello() {
  			return greetingService.sayGreeting();
  		}
  	}

  	@Service("i18nService")
  	public class I18nEnglishGreetingService implements GreetingService {
  		@Override
  		public String sayGreeting() {
  			return "Hello World - EN";
  		}
  	}

  	@Service("i18nService")
  	public class I18nSpanishGreetingService implements GreetingService {
  		@Override
  		public String sayGreeting() {
  			return "Hola Mundo - ES";
  		}
  	}

  	OUTPUT:
  		2020-08-20 13:12:13.319 ERROR 15072 --- [           main] o.s.boot.SpringApplication               : Application run failed

  		org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [guru.springframework.sfgdi.SfgDiApplication]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'i18nService' for bean class [guru.springframework.sfgdi.service.I18nSpanishGreetingService] conflicts with existing, non-compatible bean definition of same name and class [guru.springframework.sfgdi.service.I18nEnglishGreetingService]
  			at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:188) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
  			at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:319) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
  			at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:236) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
  			...
  			at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
  			at guru.springframework.sfgdi.SfgDiApplication.main(SfgDiApplication.java:12) ~[classes/:na]
  		Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'i18nService' for bean class [guru.springframework.sfgdi.service.I18nSpanishGreetingService] conflicts with existing, non-compatible bean definition of same name and class [guru.springframework.sfgdi.service.I18nEnglishGreetingService]
  			at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.checkCandidate(ClassPathBeanDefinitionScanner.java:349) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
  			...
  			at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:174) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
  			... 13 common frames omitted

  	ROOT CAUSE:

  		Two service beans were given the exact same qualifier name via @Service("i18nService")

  	FIX:
  		Add a unique @Profile value to each conflicting service bean

  		@Profile("EN")
  		@Service("i18nService")
  		public class I18nEnglishGreetingService implements GreetingService {
  			...
  		}

  		@Profile("ES")
  		@Service("i18nService")
  		public class I18nSpanishGreetingService implements GreetingService {
  			...
  		}

  		In application.properties, activate one of those profile values. Beans which have @Profile will only be loaded if they have a matching profile value!

  		spring.profiles.active=ES

  	OUTPUT:
  		Hola Mundo - ES